export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-primary-container": "#554300",
              "on-secondary": "#003642",
              "surface-bright": "#393939",
              "surface-variant": "#353535",
              "primary-container": "#d4af37",
              "on-tertiary-container": "#254188",
              "primary-fixed": "#ffe088",
              "error": "#ffb4ab",
              "surface-container": "#1f1f1f",
              "on-secondary-fixed-variant": "#004e5f",
              "tertiary-container": "#97b0ff",
              "secondary-fixed": "#b4ebff",
              "on-secondary-container": "#005669",
              "on-tertiary-fixed-variant": "#27438a",
              "error-container": "#93000a",
              "on-tertiary": "#082b72",
              "on-surface": "#e2e2e2",
              "secondary-fixed-dim": "#3cd7ff",
              "on-surface-variant": "#d0c5af",
              "surface-dim": "#131313",
              "outline-variant": "#4d4635",
              "on-background": "#e2e2e2",
              "primary-fixed-dim": "#e9c349",
              "inverse-primary": "#735c00",
              "tertiary-fixed": "#dbe1ff",
              "secondary": "#a2e7ff",
              "on-primary": "#3c2f00",
              "tertiary": "#bfcdff",
              "on-error": "#690005",
              "surface": "#131313",
              "surface-container-lowest": "#0e0e0e",
              "surface-container-high": "#2a2a2a",
              "outline": "#99907c",
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed": "#00174b",
              "background": "#131313",
              "secondary-container": "#00d2fd",
              "primary": "#f2ca50",
              "surface-tint": "#e9c349",
              "inverse-on-surface": "#303030",
              "on-primary-fixed-variant": "#574500",
              "on-secondary-fixed": "#001f27",
              "inverse-surface": "#e2e2e2",
              "surface-container-highest": "#353535",
              "surface-container-low": "#1b1b1b",
              "tertiary-fixed-dim": "#b4c5ff",
              "on-primary-fixed": "#241a00"
      },
      "borderRadius": {
              "DEFAULT": "0px",
              "lg": "0px",
              "xl": "0px",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Newsreader", "serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
