export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#f2ca50",
        "on-secondary": "#1a0900",
        "background": "#0b0e11",
        "tertiary-container": "#4edea3",
        "primary-container": "#f2ca50",
        "on-primary-fixed": "#1a0900",
        "outline-variant": "#2b3139",
        "on-tertiary-fixed": "#002113",
        "outline": "#474d57",
        "surface-container-lowest": "#0b0e11",
        "secondary-fixed-dim": "#f2ca50",
        "surface": "#0b0e11",
        "surface-container": "#181a20",
        "surface-dim": "#0b0e11",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-highest": "#2b3139",
        "primary-fixed-dim": "#f2ca50",
        "on-secondary-container": "#1a0900",
        "on-primary-container": "#1a0900",
        "primary-fixed": "#fde047",
        "on-tertiary": "#003824",
        "surface-variant": "#1e2329",
        "on-secondary-fixed": "#1a0900",
        "on-primary": "#1a0900",
        "tertiary": "#4edea3",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        "inverse-primary": "#d97706",
        "primary": "#f2ca50",
        "surface-container-low": "#1e2329",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#d97706",
        "surface-container-high": "#2b3139",
        "on-surface": "#eaecef",
        "error": "#f6465d",
        "on-tertiary-container": "#00311f",
        "inverse-surface": "#eaecef",
        "surface-bright": "#2b3139",
        "secondary-container": "#f2ca50",
        "secondary": "#f2ca50",
        "on-background": "#eaecef",
        "on-surface-variant": "#848e9c",
        "on-primary-fixed-variant": "#d97706",
        "secondary-fixed": "#f2ca50",
        "on-tertiary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "inverse-on-surface": "#0b0e11",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        sm: "16px",
        gutter: "24px",
        md: "24px",
        xl: "80px",
        lg: "48px",
        base: "4px",
        xs: "8px",
      },
      fontFamily: {
        h1: ["Space Grotesk", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        mono: ["monospace"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.02em" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        mono: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
